spring:
  # 数据源配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/journey?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  # servlet配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # 自定义配置
  config:
    import: application-custom.yml

# 日志配置
logging:
  level:
    root: info
    com.journey.mapper: debug